# Generated by Django 2.2.14 on 2020-12-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, null=True)),
                ('autor', models.CharField(max_length=200)),
                ('fecha_comentario', models.DateField()),
                ('contenido', models.CharField(max_length=2000)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.Publicacion')),
            ],
        ),
    ]
